### ISSUE TITLE
Cannot reproduce example of setting the output format

### ISSUE THREAD

**Issue by mirkov** [lispm/measures#1]
First, thank you for providing ``measures''.

I want to try setting the output format.  I use the example in *measures-usage.text*:

    (setf (ms-output-format (measure-named "distance"))
          '(:best-fit "mm" "m" "km"))

and encounter problems discussed below.  I may be doing something wrong, but I don't see what that could be.

<a id="org611f7b1"></a>

# Verbatim use of the example

The verbatim use of the example with the distance in quotes, leads to error:

    MS> (setf (ms-output-format (measure-named "distance"))
    	  '(:best-fit "mm" "m" "km"))

Debug info:

    Not a measure: distance.
       [Condition of type SIMPLE-ERROR]
    
    Restarts:
     0: [RETRY] Retry SLIME REPL evaluation request.
     1: [*ABORT] Return to SLIME's top level.
     2: [ABORT-BREAK] Reset this thread
     3: [ABORT] Kill this thread
    
    Backtrace:
      0: (MEASURE-NAMED "distance" :ERROR-P T)
      1: (#<Anonymous Function #x210176E86F>)
      2: (CCL::CHEAP-EVAL (SETF (MS-OUTPUT-FORMAT (MEASURE-NAMED "distance")) '(:BEST-FIT "mm" "m" "km")))
      3: (SWANK::EVAL-REGION "(setf (ms-output-format (measure-named \"distance\"))\n          '(:best-fit \"mm\" \"m\" \"km\"))\n")

<a id="orgc03d4ae"></a>

# Use symbol instead of string

Using a symbol instead for string for *distance*, I can modify
the output format.  But its application leads to an error

    CL-USER> (in-package :ms)
    #<Package "MEASURES">
    MS> (setf (ms-output-format (measure-named 'distance))
    	  '(:best-fit "mm" "m" "km"))
    (:BEST-FIT "mm" "m" "km")
    MS> #m1000m

Debug trace:

     0: (CCL::=-2 "km" 0)
     1: (PRINT-FORMATTED-DIM 1000 \m "km" #<STRING-OUTPUT-STREAM  #x2101719BED>)
     2: (#<CCL::STANDARD-KERNEL-METHOD PRINT-OBJECT (T T)> #<error printing XDIM-NUMBER #x2101719D7D> #<STRING-OUTPUT-STREAM  #x2101719BED>)
     3: (CCL::%CALL-NEXT-METHOD (NIL #<CCL::STANDARD-KERNEL-METHOD PRINT-OBJECT (T T)> . 82244322))
     4: (CCL::%%STANDARD-COMBINED-METHOD-DCODE (#<CCL::STANDARD-KERNEL-METHOD PRINT-OBJECT :AROUND (T T)> #<CCL::STANDARD-KERNEL-METHOD PRINT-OBJECT (T T)>) 82244322)
     5: (NIL #<Unknown Arguments>)
     6: (CCL::WRITE-A-FROB #<error printing XDIM-NUMBER #x2101719D7D> #<STRING-OUTPUT-STREAM  #x2101719BED> 1152921504606846975 NIL)
     7: (CCL::WRITE-INTERNAL #<STRING-OUTPUT-STREAM  #x2101719BED> #<error printing XDIM-NUMBER #x2101719D7D> 1152921504606846975 NIL)
     8: (CCL::WRITE-1 #<error printing XDIM-NUMBER #x2101719D7D> #<STRING-OUTPUT-STREAM  #x2101719BED> 1152921504606846975)
     9: (PRIN1 #<error printing XDIM-NUMBER #x2101719D7D> #<STRING-OUTPUT-STREAM  #x2101719BED>)
    10: (PRIN1-TO-STRING #<error printing XDIM-NUMBER #x2101719D7D>)
    11: ((:INTERNAL SWANK/BACKEND:SEND SWANK::PRESENT-REPL-RESULTS) #<error printing XDIM-NUMBER #x2101719D7D>)
    12: (SWANK::PRESENT-REPL-RESULTS (#<error printing CONS #x2101719D53>)
    13: (SWANK-REPL::TRACK-PACKAGE #<CCL:COMPILED-LEXICAL-CLOSURE (:INTERNAL SWANK-REPL::REPL-EVAL) #x210171A26F>)
    14: (SWANK::CALL-WITH-RETRY-RESTART "Retry SLIME REPL evaluation request." #<CCL:COMPILED-LEXICAL-CLOSURE (:INTERNAL SWANK-REPL::REPL-EVAL) #x210171A2EF>)
    15: (SWANK::CALL-WITH-BUFFER-SYNTAX NIL #<CCL:COMPILED-LEXICAL-CLOSURE (:INTERNAL SWANK-REPL::REPL-EVAL) #x210171A32F>)
    16: (SWANK-REPL::REPL-EVAL "#m1000m\n")
    ...

**Comment by lispm** [comment]
Sadly there is some difference between this version and the old docs.

Best use the exported operators from package MEASURES, short MS.

Finding a measure by symbol is okay.

To define a unit format use MS:DEFINE-UNIT-FORMAT:

    (ms:define-unit-format ms:distance :best-fit "mm" "m" "km")

**Comment by mirkov** [comment]
Thank you for the suggestion.

It might be possible to make `(setf (ms-output-format ...))` work adding an **around** method like so:
```
(defmethod (setf ms-output-format) :around (fd (ms measure))
  "Ensure the format descriptor FD is valid prior to calling the setf method

For instance, when using :BEST-FIT, the FD list has to terminate with a NIL.  
This around method fixes FD and then issues a CALL-NEXT-METHOD with a fixed-up FD"
  (let ((fd-valid (valid-format-desc fd ms)))
    (CALL-NEXT-METHOD fd-valid ms)))
```
I only lightly tested this.  I am not sure whether this would break some other code under more intensive use.

I will keep it in my local branch for now to see how it performs.

**Comment by lispm** [comment]
Possible, but now a function like MS::SET-UNIT-FORMAT calls MS::VALID-FORMAT-DESC twice. Which is harmless, but one too much.

**Comment by mirkov** [comment]
Good catch.

Since the around method eliminates the need for MS::SET-UNIT-FORMAT to call MS::VALID-FORMAT-DESC it could be simplified to:

```
(defun set-unit-format (ms format-desc)
  (if (symbolp ms) (setq ms (measure-named ms)))
  (setf (ms-output-format ms) format-desc))
```

(Also the IF should be a WHEN)

Actually I am not too thrilled with my around method. It is a bit too intruding for my taste.
I would prefer if a before method could do the job, but I did not spend time on figuring out if that could be made to work.

Maybe the simplest thing is:

- follow your advice to use the macro
- fix the documentation not to use `(setf (ms-output-format`
- change the slot accessor to reader to eliminate the possibility of the `(setf (ms-output-format` call
